# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [1]:
# import NumPy into Python

import numpy as np
# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(5001, size=(1000, 20))
print(X)
# print the shape of X
print(X.shape)


[[ 786 1277 1715 ... 2069 3624  179]
 [1162 4925  195 ... 3047 2622 1389]
 [3095 2590  957 ... 3655 2946 3021]
 ...
 [1664 1611 1396 ... 2996 4110 2822]
 [  41  317 4560 ... 3865 4223 4929]
 [1932 4717 3372 ... 4520 1654 4390]]
(1000, 20)


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [2]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)
print(ave_cols)
# Standard Deviation of the values in each column of X
std_cols = np.std(X,axis=0)
print(std_cols)

[2508.97  2502.894 2542.465 2501.919 2506.308 2464.179 2509.893 2445.523
 2454.87  2542.267 2476.242 2597.851 2529.545 2511.723 2543.971 2481.463
 2524.953 2470.253 2484.653 2514.266]
[1446.64602688 1410.00132013 1443.74141271 1447.52418441 1450.41118278
 1410.00147623 1429.55782029 1425.96353581 1466.73678453 1452.1125768
 1451.0023058  1437.73979037 1445.00434324 1461.79448154 1441.26966323
 1485.0490755  1437.89448528 1424.61725281 1446.75935684 1461.64208726]


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [3]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [4]:
# Mean normalize X
X_norm = X-(X*[ave_cols/std_cols])

print(X_norm)

[[ -577.18794187  -989.8032947  -1305.15820604 ... -1518.59761398
  -2599.82874488  -128.90958876]
 [ -853.29820414 -3817.36979358  -148.39991264 ... -2236.42674229
  -1881.00192304 -1000.30960216]
 [-2272.76931308 -2007.51020617  -728.30110973 ... -2682.68452349
  -2113.43694327 -2175.61937229]
 ...
 [-1221.9347777  -1248.68685025 -1062.39116947 ... -2198.99393499
  -2948.48127524 -2032.30647753]
 [  -30.10776796  -245.70684763 -3470.27488021 ... -2836.81961239
  -3029.54657551 -3549.69476532]
 [-1418.73677314 -3656.14889671 -2566.17695089 ... -3317.57429444
  -1186.56643047 -3161.52566844]]


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [5]:
# Print the average of all the values of X_norm

print(np.average(X_norm))
# Print the average of the minimum value in each column of X_norm
print(np.average(X_norm - X_norm.min(axis=0)))

# Print the average of the maximum value in each column of X_norm
print(np.average(X_norm - X_norm.max(axis=0)))


-1844.4630479483496
1832.2768264604747
-1842.0329668637653


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [6]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([2, 0, 3, 4, 1])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [7]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices =np.random.permutation(X_norm.shape[0])
print(row_indices)

[204 261 600 981 712 294 758 296  94 970 338 754 505 570 343  40 307 850
 771 865  41 719 520 756 192 832 729 924 499 863 783 835  21 820 268 528
 344 677 359 748 412 484 384 455 250 521 731 608 493 797 223 413 123 439
 630 264 613 256 356 930  45 720 205 541 102 814 472 477 454 846 501 225
 300 315 958 458 580 422 112 306 561 213 993 162 945 904 311 826 716  74
 305 218 999 399 659 898 130 103 885 379 639 695 743 497 407 259 852 687
 920 188 775 544 701 723  67 560 461  51 232 700 416 548 711 636 215 618
 220 738 968 891 152 538 126  93 864 974 502 940 417 923 325 880  84 876
  48 117 660 601 158 831  85 150 246 915 989 387 928  52 357 127 511 807
  97 734 182 894 243 746 241 512 327 423 822 985 301 173 593   7 391 887
 938 525 889 408 196 575 871 706 532 884  20 688  73 536 169 691  78 492
 462 679 892 905  79 257 577 901  61 436 549  95 153  36 125 490 947 120
 331 730 287  98 322 394 473 283 556 808 444 906 592 518 318 742 288 811
  81 689 878 481 390 441 685 802 380 230 179  92 19

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [8]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = row_indices[:12]

# Create a Cross Validation Set
X_crossVal = row_indices[7:8]

# Create a Test Set
X_test = row_indices[81:100]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [9]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(12,)
(1,)
(19,)
